Add mentorship view (#16)
TerrapinFreelancers/bitcamp-app pull request #19
Opened 2016-10-16 16:07 UTC by jsjqian

Resolves #16 

Adds a WebView to contain the mentorship.bitca.mp page. 
Currently working for Android, will need someone to test it on iOS to ensure functionality.
Most of this code is pulled straight from https://facebook.github.io/react-native/docs/webview.html
Much of the styling needs to be redesigned, that is up to @AyeAndy 
Still need to eventually redesign the mentorship page

2016-10-16 19:54 UTC, goccert25 commented
LGTM on iOS

2016-10-17 01:00 UTC, jdai8 requested changes

2016-10-17 01:00 UTC, jdai8 commented on scenes/MentorsScene.js
> +var HEADER = '#1A2E33';
Can we put these into the shared styles file?

2016-10-17 01:00 UTC, jdai8 commented on scenes/MentorsScene.js
> +var TEXT_INPUT_REF = 'urlInput';
we never use this

2016-10-17 01:00 UTC, jdai8 commented on scenes/MentorsScene.js
> +          ref={WEBVIEW_REF}
Use a callback function instead
https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute

2016-10-17 01:00 UTC, jdai8 commented on scenes/MentorsScene.js
> +import { View, Text, WebView, ScrollView, TextInput, TouchableWithoutFeedback, TouchableOpacity, StyleSheet } from 'react-native';
80 character lines

2016-10-23 21:23 UTC, jdai8 approved these changes

2016-10-24 02:17 UTC, merged